# Generated by Django 2.0.4 on 2018-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rustbot', '0003_auto_20180422_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustbotchat',
            name='tag_mask',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rustbotstore',
            name='tag',
            field=models.IntegerField(default=1),
        ),
    ]
